### ISSUE TITLE
Typo in sample code in read-me file

### ISSUE THREAD

**Issue by mklement0** [dapplo/Dapplo.ActiveDirectory#6]
`public interface IUserInfo : IAdObject`

should presumably be:

`public class UserInfo : IAdObject` and therefore `query.Execute<UserInfo>`

**Comment by Lakritzator** [comment]
Actually, no... You can use interfaces, and you will become a proxied object instance back.

It was briefly removed, but I placed it back with a better solution.
Try it out with the current version 0.2.17

**Comment by mklement0** [comment]
Got it, thanks.
